### ISSUE TITLE
Implement daily today's fixture publishing on a channel

### ISSUE THREAD

**Issue by RazvanBerbece** [fhatti/unifyBOT#2]
## Summary
As a member of the Unify Football Discord community I want to have a channel that I can check every day to see what today's fixtures are. The league can be chosen by the developer, and can be configured as an environment variable.

## Requirements
- [x] create / pick a channel to send the updates to
- [x] ensure that at an arbitrary time every day, the embed is sent to the channel
- [ ] maybe somehow integrate what is used for `/today` ? abstract ;)
- [x] any other fun / useful things to display ?

**Comment by fhatti** [comment]
Some extra requirements for this feature : 
- [x] Implement either a slash command (/getRole) or a dedicated channel where users can assign themselves roles (e.g., "La Liga fan", "Premier League fan").
- [x] Access Control: Users must have the relevant role to gain access to the "Today Matches" channel.
- [x] Role Management: Allow users to add or remove roles easily.
